# dev version of docker compose
# before docker-compose up tsc --watch must started
version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./deploy/frontend/Dockerfile
    hostname: frontend
    networks:
      - overlay
    ports:
      - '4200:80'
  api:
    build:
      context: ./
      dockerfile: ./deploy/api/Dockerfile
    hostname: api
    networks:
      - overlay
    ports:
      - '3333:3333'
  postgres:
    image: "postgres:10-alpine"
    hostname: "postgres"
    networks:
      - overlay
    environment:
     POSTGRES_PASSWORD: ilt0q1drzye
     POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
volumes:
  postgres_data:
  redis_data:
  minio-data:
  pgadmin:
networks:
  overlay:
