# dev version of docker compose
# before docker-compose up tsc --watch must started
version: '3'

services:
  postgres:
    image: "postgres:10-alpine"
    hostname: "postgres"
    networks:
      - overlay
    environment:
     POSTGRES_PASSWORD: ilt0q1drzye
     POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - overlay
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    hostname: "redis"
    networks:
      - overlay
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
volumes:
  postgres_data:
  redis_data:
  minio-data:
  pgadmin:
networks:
  overlay:
